// <auto-generated />
using BikerXY.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BikerXY.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629151431_AgregarTablaUsuarios")]
    partial class AgregarTablaUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikerXY.Models.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Motos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Deportiva",
                            Cilindrada = 998,
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZZoQ8llcmttyfWYYJbC4VKwJuhSjNJgnvykkFha1Yz5FcRnVsH_ZvE8g&s=10",
                            Marca = "Yamaha",
                            Modelo = "R1",
                            Precio = 17500.00m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Adventure",
                            Cilindrada = 1084,
                            ImagenUrl = "https://www.doble.co.uk/i/1295/oct2023-honda-africatwin-advsports-cover.webp?r=6161",
                            Marca = "Honda",
                            Modelo = "Africa Twin",
                            Precio = 14800.00m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Naked",
                            Cilindrada = 948,
                            ImagenUrl = "https://motoblog.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-29-at-14.20.43.jpeg",
                            Marca = "Kawasaki",
                            Modelo = "Z900",
                            Precio = 9300.00m
                        });
                });

            modelBuilder.Entity("BikerXY.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
