// <auto-generated />
using System;
using BikerXY.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BikerXY.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701155435_ExpandirModelosBikerXY")]
    partial class ExpandirModelosBikerXY
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikerXY.Models.ContactoLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MotoId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoCliente")
                        .HasColumnType("text");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactoLeads");
                });

            modelBuilder.Entity("BikerXY.Models.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EsDestacada")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GifUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Motos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2024,
                            Categoria = "Deportiva",
                            Cilindrada = 998,
                            Descripcion = "Superbike de alto rendimiento para pista y calle.",
                            EsDestacada = true,
                            Estado = "Nueva",
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZZoQ8llcmttyfWYYJbC4VKwJuhSjNJgnvykkFha1Yz5FcRnVsH_ZvE8g&s=10",
                            Marca = "Yamaha",
                            Modelo = "R1",
                            Precio = 17500.00m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2023,
                            Categoria = "Adventure",
                            Cilindrada = 1084,
                            Descripcion = "Maxitrail legendaria lista para cualquier tipo de terreno.",
                            EsDestacada = true,
                            Estado = "Nueva",
                            ImagenUrl = "https://www.doble.co.uk/i/1295/oct2023-honda-africatwin-advsports-cover.webp?r=6161",
                            Marca = "Honda",
                            Modelo = "Africa Twin",
                            Precio = 14800.00m,
                            Stock = 2
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2024,
                            Categoria = "Naked",
                            Cilindrada = 948,
                            Descripcion = "Estilo Sugomi puro con aceleración agresiva y ágil.",
                            EsDestacada = false,
                            Estado = "Nueva",
                            ImagenUrl = "https://motoblog.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-29-at-14.20.43.jpeg",
                            Marca = "Kawasaki",
                            Modelo = "Z900",
                            Precio = 9300.00m,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("BikerXY.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BikerXY.Models.VentaReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MotoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MotoId");

                    b.ToTable("VentaReservas");
                });

            modelBuilder.Entity("BikerXY.Models.VentaReserva", b =>
                {
                    b.HasOne("BikerXY.Models.Moto", "Moto")
                        .WithMany()
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");
                });
#pragma warning restore 612, 618
        }
    }
}
