// <auto-generated />
using BikerXY.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BikerXY.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629125922_CorregirImagenKawasaki")]
    partial class CorregirImagenKawasaki
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikerXY.Models.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Motos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Deportiva",
                            Cilindrada = 998,
                            ImagenUrl = "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=600",
                            Marca = "Yamaha",
                            Modelo = "R1",
                            Precio = 17500.00m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Adventure",
                            Cilindrada = 1084,
                            ImagenUrl = "https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?q=80&w=600",
                            Marca = "Honda",
                            Modelo = "Africa Twin",
                            Precio = 14800.00m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Naked",
                            Cilindrada = 948,
                            ImagenUrl = "https://images.unsplash.com/photo-1609630875171-b1321377ee65?q=80&w=600",
                            Marca = "Kawasaki",
                            Modelo = "Z900",
                            Precio = 9300.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
